{{
    config(
        materialized="table"
    )
}}

select
    productid,
    name,
    safetystocklevel,
    finishedgoodsflag,
    class,
    makeflag,
    productnumber,
    reorderpoint,
    modifieddate,
    rowguid,
    productmodelid,
    weightunitmeasurecode,
    standardcost,
    productsubcategoryid,
    listprice,
    daystomanufacture,
    productline,
    color,
    sellstartdate,
    weight,
    valid_from,
    valid_to
from {{ source('bike_business', 'ops_product_history') }}
