version: 2

sources:
  - name: bike_business
    database: business_operations
    schema: raw
    tables:
      - name: fx_latest_rate
      - name: sentiment
      - name: ops_address_history
      - name: ops_country_region
      - name: ops_credit_card
      - name: ops_customer
      - name: ops_person
      - name: ops_product_category
      - name: ops_product_history
      - name: ops_product_subcategory
      - name: ops_purchasing_history
      - name: ops_salesorderdetail
      - name: ops_salesorderheadersalesreason
      - name: ops_salesorderheader_history
      - name: ops_salesreason
      - name: ops_stateprovince
      - name: ops_store
      - name: ops_workorder
